### ISSUE TITLE
make code more pythonic

### ISSUE THREAD

**Issue by sibalzer** [sibalzer/impfbot#44]
- [x]  settings.py

- [x]  impfbot.py

- [x] alerts.py

- [x] api_wrapper.py

- [x] common.py

**Comment by paulypeter** [comment]
- [ ] `config_generator.py`

could also use some improvements

**Comment by paulypeter** [comment]
@sibalzer 

For `settings.py`:
Since everything is checked now (as of 9310053) all of the code after config generation is obsolete and only needs to be run when a config.ini is provided by the user. We could move it to a separate function then.

Also, I'd suggest using one const `NOTIFIERS` used by `config_generator.py`, `settings.py`, `alerts.py` and wherever else it might be needed. This way, we could reduce lines of code in several places.

**Comment by sibalzer** [comment]
> Also, I'd suggest using one const `NOTIFIERS` used by `config_generator.py`, `settings.py`, `alerts.py` and wherever else it might be needed. This way, we could reduce lines of code in several places.

i've over engineered `settings.py` [make-code-more-pythonic](https://github.com/sibalzer/impfbot/tree/make-code-more-pythonic) for v3.0.0 making use of `NOTIFIERS`. `alerts.py` is in queue.

**Comment by paulypeter** [comment]
Looks great!
That's a lot of changes though, we'll have to make sure everything works as expected.

**Comment by sibalzer** [comment]
I've written tests this time to be save 😅 (tests for `settings.py` still missing). Still, i'll test everything manually before the release to be on the safe side.

**Comment by sibalzer** [comment]
5/5 yay

**Comment by sibalzer** [comment]
closed by #83
